apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: hsujaytest 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hsujaytest 
    spec:
      containers:
        - name: hsujaytest 
          image: test233.azurecr.io/hsujaytest
          ports:
          - containerPort: 8080